### ISSUE TITLE
Feature : Choose name of imported loadout

### ISSUE THREAD

**Issue by Mazwak** [NumyAddon/TalentLoadoutManager#10]
Hello

At the moment, TLM loads every spec into « talentloadoutmanager ».

It would be nice to have a choice.

Either finite, like a combo with Raid/M+/PvP/OpenWorld.

Either totally free.

It would make it easier for spell bar management.

**Comment by Numynum** [comment]
I added this as a feature in an alpha build
it _should_ work, but I'm not playing enough atm to properly test it 🙂

**Comment by Mazwak** [comment]
It works ! (almost)

I can create custom loadout assigned to an 'official' loadout.

The UI is good.

However, it does not switch the 'official' talent.

I could not reproduce reliably, but it happened.

Let’s say I’m in custom loadout 'Uldaman' set to load in official 'M+'.
I select custom 'Rashok' in 'official' set 'Aberrus'.

It does load the talents, but it does not switch the official one.
So I’m left with my M+ bars and not the raid bars.


Also, if I go from an M+/Ulda to Raid/Rashok and then M+/Brackenhide, it will change twice, which cannot be avoided I think.
There should be a message somewhere, at bottom ou popup.

**Comment by Numynum** [comment]
I'll see if I can find out what's going on with it

when it comes to switching between custom loadouts that are under different 'official'/blizzard loadouts, yeah it has to first load the blizzard loadout, and then load the custom loadout
unfortunately that's due to a blizzard bug, I really wish that bug didn't exist, because then I could switch loadouts with only ever 1 channel, but well.. can't be helped
I'm not really sure how I would inform a user about that, without it getting super annoying though, especially if you switch between loadouts often

**Comment by Mazwak** [comment]
Don’t search too much.

I can’t reproduce it anymore.

the feature is good enough for me as is.
